#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  BallistaAxis,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  BallistaFire,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  AutonomousModeSwitch, sensorTouch)
#pragma config(Sensor, I2C_1,  LeftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LMDrive,       tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           RMDrive,       tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           LRRDrive,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           LRFDrive,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           RRRDrive,      tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           RRFDrive,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           BallistaAxis,  tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port8,           BallIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BallistaFire,  tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(DatalogSeries, 0, "Main Battery Level", Properties, immediateBatteryLevel, , 50)
#pragma config(DatalogSeries, 1, "Backup Battery Level", Properties, BackupBatteryLevel, , 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                         VEXnet Joystick Weirdness                         */
/*                                                                           */
/*	So the joysticks on the VEXnet controller are labled weirdly.  Because   */
/*	of this, keep the following in mind when progamming it.  Up and down on  */
/*	the right stick is channel 1.  Left and right on the right stick is      */
/*	channel 0.  Up and down on the left stick is channel 2, and left and     */
/*	right on the left stick is channel 3.  If you are having problems with   */
/*	controls, make sure that you have the channels set correctly!  If you    */
/*	mess up, it's entirely your fault!                                       */
/* 		- Robbie                                                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                             Sensor Notes                                  */
/*                                                                           */
/*	 - Shaft Encoders > 360 counts per revolution (1 count = 1 degree)       */
/*	 - IMEs > 627.2 counts per revolution                                    */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                     Variable and Function Definitions                     */
/*                                                                           */
/*---------------------------------------------------------------------------*/

//int ballistaPosition = 0;
//bool ballistaBtnPressed = false;
bool fireBtnPressed = false;
bool intakeOn = true;
bool intakeBtnPressed = false;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  resetMotorEncoder(LMDrive);
  resetMotorEncoder(RMDrive);
	//resetMotorEncoder(BallistaAxis);

  bStopTasksBetweenModes = true;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[BallIntake] = 127;
  if (SensorValue[AutonomousModeSwitch] == 1)
  {
		// Move to get a ball off the center podium, starting from the close alliance
  	// starting zone, then move to a certain position
  }
  else
  {
		// Move to get a ball off the center podium, starting from the far alliance
  	// starting zone, then move to the same position
	}
	// Move into position to fire a ball, and fire a ball, then move into position
	// to fire a second ball and fire a second ball
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	motor[BallIntake] = 127;
  while (true)
  {
  	// Left side drive motors
  	motor[LMDrive] = vexRT[2];
  	motor[LRFDrive] = vexRT[2];
  	motor[LRRDrive] = vexRT[2];


  	// Right side drive motors
  	motor[RMDrive] = vexRT[1];
  	motor[RRFDrive] = vexRT[1];
  	motor[RRRDrive] = vexRT[1];

/*
  	// Ballista Positioning
  	if (vexRT[Btn8R] == 1)
  	{
			ballistaBtnPressed = true;
  	}
  	if (vexRT[Btn8R] == 0 && ballistaBtnPressed == true)
  	{
  		ballistaBtnPressed = false;
  		int pos = SensorValue[BallistaAxis]
  		if (ballistaPosition == 0)
  		{
  			while (SensorValue[BallistaAxis] < pos+n)
  			{
  				motor[BallistaAxis] = 127;
  			}
  			motor[BallistaAxis] = 0;
  			ballistaPosition = 1;
  		}
  		else
  		{
  			while (SensorValue[BallistaAxis] > pos-n)
  			{
  				motor[BallistaAxis] = -127;
  			}
  			motor[BallistaAxis] = 0;
  			ballistaPosition = 0;
  		}
  	}
*/

		// Ballista firing mechanism
		if (vexRT[Btn7L] == 1)
  	{
  		fireBtnPressed = true;
  	}
  	if (vexRT[Btn7L] == 0 && fireBtnPressed == true)
  	{
  		fireBtnPressed = false;
  		int pos = SensorValue[BallistaFire];
  		setMotorTarget(BallistaFire, pos+360, 127, true);
  	}


  	// Ball intake toggle
  	if (vexRT[Btn7L] == 1)
  	{
  		intakeBtnPressed = true;
  	}
  	if (vexRT[Btn7L] == 0 && intakeBtnPressed == true)
  	{
  		intakeBtnPressed = false;
  		if (intakeOn == true)
  		{
  			motor[BallIntake] = 0;
  			intakeOn = false;
  		}
  		else
  		{
  			motor[BallIntake] = 127;
  			intakeOn = true;
  		}
  	}
  }
}
