#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    AutonomousModeSwitch, sensorAnalog)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  LeftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LMDrive,       tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           RMDrive,       tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           LRRDrive,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           LRFDrive,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           RRRDrive,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           RRFDrive,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           BallistaAxis,  tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(DatalogSeries, 0, "Main Battery Level", Properties, immediateBatteryLevel, , 50)
#pragma config(DatalogSeries, 1, "Backup Battery Level", Properties, BackupBatteryLevel, , 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                         VEXnet Joystick Weirdness                         */
/*                                                                           */
/*	So the joysticks on our VEXnet controller are acting up.  Because of     */
/*	this, keep the following in mind when progamming it.  Up and down on the */
/*	right stick is channel #.  Left and right on the right stick is          */
/*	channel #.  Up and down on the left stick is channel #, and left and     */
/*	right on the left stick is channel #.  If you are having problems with   */
/*	controls, make sure that you have the channels set correctly!  If you    */
/*	mess up, it's entirely your fault!                                       */
/* 		- Robbie                                                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                             Sensor Notes                                  */
/*                                                                           */
/*	 - Shaft Encoders > 360 counts per revolution (1 count = 1 degree)       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                     Variable and Function Definitions                     */
/*                                                                           */
/*---------------------------------------------------------------------------*/

int ballistaPosition = 0;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  resetMotorEncoder(LMDrive);
  resetMotorEncoder(RMDrive);

  bStopTasksBetweenModes = true;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  if (SensorValue[AutonomousModeSwitch] == 1)
  {
		// Move to get a ball off the center podium, starting from the close alliance
  	// starting zone, then move to a certain position
  }
  else
  {
		// Move to get a ball off the center podium, starting from the far alliance
  	// starting zone, then move to the same position
	}
	// Move into position to fire a ball, and fire a ball, then move into position
	// to fire a second ball and fire a second ball
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  while (true)
  {
  	// Left side drive motors
  	motor[LMDrive] = vexRT[1];
  	motor[LRFDrive] = vexRT[1];
  	motor[LRRDrive] = vexRT[1];
  	// Right side drive motors
  	motor[RMDrive] = vexRT[2];
  	motor[RRFDrive] = vexRT[2];
  	motor[RRRDrive] = vexRT[2];

  	// Ballista Positioning
  	if (vexRT[Btn8R] == 1 && ballistaPosition == 0)
  	{
  		int pos = SensorValue[BallistaAxis];
  		while (SensorValue[BallistaAxis] < pos+n)
  		{
  			motor[BallistaAxis] = Speed;
  		}
  		motor[BallistaAxis] = 0;
  		ballistaPosition = 1;
  	}
  	else if (vexRT[Btn8R] == 1 && ballistaPosition == 1)
  	{
  		while (SensorValue[BallistaAxis] > pos-n)
  		{
  			motor[BallistaAxis] = Speed;
  		}
  		motor[BallistaAxis] = 0;
  		ballistaPosition = 0;
  	}
  }
}
